[features]
seeds = false
skip-lint = false
[programs.localnet]
anchor_escrow = "5pb3J14HvvTJaBV8MfQxkNPProsspUZJJ2YAm28xpzD9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/lap02139/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
